networks:
  tessellation-network:
    driver: bridge

services:
  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gl0:
    image: constellationnetwork/tessellation${CL_DOCKER_CORE_REPO:-}:${DOCKER_IMAGE_VERSION:-latest}
    networks:
      - tessellation-network
    restart: unless-stopped
    env_file:
      - gl0.env
    ports:
      - "9000:9000"  # Public HTTP
      - "9001:9001"  # P2P HTTP
    volumes:
      - ./gl0/data:/app/data
      - ./gl0/logs:/app/logs
      - ./key.p12:/app/key.p12:ro
      - ./seedlist:/app/seedlist:ro
    healthcheck:
      test: ["CMD", "cpilotHC"]
#      test: ["CMD", "/health-check/bin/run.sh"]
      interval: 15s
      retries: 1
      timeout: 15s
      start_period: 60s
    profiles: ["gl0"]
    labels:
      autoheal: "true"
  gl1:
    image: constellationnetwork/tessellation${CL_DOCKER_CORE_REPO:-}:${DOCKER_IMAGE_VERSION:-latest}
    restart: unless-stopped
    networks:
      - tessellation-network
    env_file:
      - gl1.env
    ports:
      - "9010:9010"  # Public HTTP
      - "9011:9011"  # P2P HTTP
    volumes:
      - ./gl1/data:/app/data
      - ./gl1/logs:/app/logs
      - ./key.p12:/app/key.p12:ro
#    healthcheck:
#      test: ["CMD", "/app/internal-health-check.sh"]
#      interval: 3s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
    profiles: ["gl1"]
