networks:
  tessellation-network:
    driver: bridge

#volumes:
#  gl0-data:
#    name: gl0-data
#  gl1-data:
#    name: gl1-data

services:
  gl0:
    image: constellationnetwork/tessellation${CL_DOCKER_CORE_REPO:-}:${DOCKER_IMAGE_VERSION:-latest}
    container_name: gl0
    networks:
      - tessellation-network
#    restart: unless-stopped
    env_file:
      - gl0.env
    ports:
      - "9000:9000"  # Public HTTP
      - "9001:9001"  # P2P HTTP
    volumes:
      - ./key.p12:/app/key.p12:ro
      - ./seedlist:/app/seedlist:ro
      - ./app-data/gl0-logs:/app/logs
      - ./app-data/gl0-data:/app/data
      - ${CL_DOCKER_PRIORITY_SEEDLIST:-/dev/null}:/app/priority-seedlist:ro
#    healthcheck:
#      test: ["CMD", "/app/internal-health-check.sh"]
#      interval: 15s
#      timeout: 5s
#      start_period: 30s
    profiles: ["gl0"]
  gl1:
    image: constellationnetwork/tessellation${CL_DOCKER_CORE_REPO:-}:${DOCKER_IMAGE_VERSION:-latest}
    container_name: gl1
#    restart: unless-stopped
    networks:
      - tessellation-network
    env_file:
      - gl1.env
    ports:
      - "9010:9010"  # Public HTTP
      - "9011:9011"  # P2P HTTP
    volumes:
      - ./key.p12:/app/key.p12:ro
      - ./seedlist:/app/seedlist:ro
      - ./app-data/gl1-logs:/app/logs
      - ./app-data/gl1-data:/app/data
      - ${CL_DOCKER_PRIORITY_SEEDLIST:-/dev/null}:/app/priority-seedlist:ro
#    healthcheck:
#      test: ["CMD", "/app/internal-health-check.sh"]
#      interval: 3s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
    profiles: ["gl1"]
